services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
  
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - REDIS_URL=${REDIS_URL}
  

volumes:
  postgres_data:

