# Generated by Django 5.1.1 on 2024-10-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='weight',
            field=models.IntegerField(default=1),
        ),
    ]
