# Generated by Django 5.1.2 on 2024-11-01 06:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_word_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='contest_availability',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('PUBLIC', 'Public')], default='PUBLIC', max_length=10),
        ),
        migrations.AddField(
            model_name='contest',
            name='contest_type',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('CONTEST', 'Contest')], default='CONTEST', max_length=10),
        ),
        migrations.AddField(
            model_name='contest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contest',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('contest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.contest')),
            ],
        ),
    ]
